language: python
sudo: false
python:
  - "3.4"
  - "3.5"
cache: pip
env:
  - DJANGO="Django>=1.8" DB=sqlite
install:
  - pip install -U $DJANGO --quiet
  - pip install -r requirements.txt

script:
  - echo "TODO"

notifications:
  email:
    on_success: never
    on_failure: always